---
# tasks file for nginx
- name: Enable EPEL Repository on CentOS 8
  dnf:
   name: epel-release
   state: latest
   become: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Enable EPEL Repository on CentOS 7
  yum:
   name: epel-release
   state: latest
   become: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
  
- name: installer nginx
  yum:
   name: nginx
   state: present
   
- name: creation du repo /var/www/{{ item }}/html
  file:
   path: /var/www/{{ item }}/html
   state: directory
   mode: '0755'
   owner: root
   group: root
   recurse: yes
  loop:
   "{{ sites }}"
   
- name: creation des fichiers index1.html a partir d un modele
  template:
   src: index.j2
   dest: /var/www/{{ item }}/html/index.html
  loop:
   "{{ sites }}"
   
- name: creation des repertoires des sites web
  file:
   path: /etc/nginx/sites-{{ item }}
   state: directory
  loop:
   "{{ sites_ae }}"
   
- name: modification nginx.conf
  lineinfile:
   path: /etc/nginx/nginx.conf
   regexp: '^# Settings'
   insertbefore: '^# Settings'
   line: '     include  /etc/nginx/sites-enabled/*.conf;'
   
- name: creation du server block file
  template:
   src: site_conf.j2
   dest: /etc/nginx/sites-available/{{ item }}.conf
  loop:
   "{{ sites }}"
   
- name: activer les servers
  file:
   src: /etc/nginx/sites-available/{{ item }}.conf
   dest: /etc/nginx/sites-enabled/{{ item }}.conf
   state: link
  loop:
   "{{ sites }}"
  notify:
   - reboot nginx
